[package]
name = "prtgn"
version = "0.3.0"
edition = "2024"
documentation = "https://github.com/ExoticDG/.prtgn/wiki"
readme = "README.md"
authors = ["ExoticDG"]
description = "A Protogen file extension written in Rust."
license = "GNU GPLv3"
license-file = "LICENSE"
repository = "https://github.com/ExoticDG/.prtgn"

[dependencies]
crossterm = "0.29.0"
ratatui = { version = "0.29.0", features = ["all-widgets"] }
tui-textarea = { git = "https://github.com/PRTGN-Development-Team/tui-textarea" }
clap = { version = "4.5.51", features = ["derive"] }
rodio = "0.21.1"
prtgn_encoding = "0.1.1"
color-eyre = "0.6.5"
hound = "3.5.1"

[package.metadata.rpm]
package = "prtgn"
depends = "alsa-lib-devel"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
prtgn = { path = "/usr/bin/prtgn" }

[package.metadata.deb]
depends = "libasound2-dev"
